const CREATOR_CARD_SLUG_PATTERN = /^[A-Za-z0-9_-]+$/;
const CREATOR_CARD_ACCESS_CODE_PATTERN = /^[A-Za-z0-9]{6}$/;
const CREATOR_CARD_URL_PATTERN = /^https?:\/\/.{1,192}$/;
const CREATOR_CARD_CURRENCIES = ['NGN', 'USD', 'GBP', 'GHS'];
const CREATOR_CARD_STATUSES = ['draft', 'published'];
const CREATOR_CARD_ACCESS_TYPES = ['public', 'private'];

module.exports = {
  CREATOR_CARD_SLUG_PATTERN,
  CREATOR_CARD_ACCESS_CODE_PATTERN,
  CREATOR_CARD_URL_PATTERN,
  CREATOR_CARD_CURRENCIES,
  CREATOR_CARD_STATUSES,
  CREATOR_CARD_ACCESS_TYPES,
};
